### ISSUE TITLE
Crash after repeated socket hang ups

### ISSUE THREAD

**Issue by nosmo** [equalitie/bundler#10]
Just got this after a few repeated failures - still trying to reproduce but the fact there's a crash-inducing error is a bit worrying. I plan on setting up monit for Bundler regardless but either way: 

```
error: Failed to call a resource response hook. Error: socket hang up
Failed to create bundle for /?url=https%3A%2F%2Fdistributed.deflect.ca%2F
Error: socket hang up
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at /opt/bundler/applications/proxyserver.js:96:11
    at fs.js:336:14
    at FSReqWrap.oncomplete (fs.js:99:15)
```

**Comment by nosmo** [comment]
This appears to be because the res object is being written to after already being closed.
