### ISSUE TITLE
Error when passed request for undefined

### ISSUE THREAD

**Issue by nosmo** [equalitie/bundler#21]
Just got this error - I'm not sure what triggered it, but this error indicates a need for type checking regardless: 

```
Got request for undefined

url.js:107
    throw new TypeError("Parameter 'url' must be a string, not " + typeof url)
          ^
TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:107:11)
    at Object.urlParse [as parse] (url.js:101:5)
    at Object.module.exports.sameHostPredicate (/opt/bundler/utils.js:56:29)
    at Server.handleRequests (/opt/bundler/proxyserver.js:103:26)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socket.ondata (http.js:1966:22)
    at TCP.onread (net.js:527:27)
```

I'll see if I can get anything useful about what caused it now.

**Comment by redwire** [comment]
I think this is another silly case where a request for something like a favicon or some other resource is coming through and the host it belongs to cannot be determined.

It appears this issue is actually related to the bundler proxy code and not the bundler library as indicated by
```
 at Object.module.exports.sameHostPredicate (/opt/bundler/utils.js:56:29)
 at Server.handleRequests (/opt/bundler/proxyserver.js:103:26)
```
Moved to https://github.com/equalitie/bundler-proxy/issues/3
