### ISSUE TITLE
Need to return errors to client in all cases

### ISSUE THREAD

**Issue by nosmo** [equalitie/bundler#7]
Currently our error returning is somewhat selective - could we have catch-alls in place to ensure that no matter what happens we give the client a return of some sort, in lieu of a timeout? 

For example:
```
debug: in Bundler.send/async.reduce, memo = url=http://localhost/favicon.ico, strictSSL=false, rejectUnauthorized=false
debug: in Bundler.send/async.reduce, memo = url=http://localhost/favicon.ico, strictSSL=false, rejectUnauthorized=false,
debug: in Bundler.send/async.reduce, memo = url=http://localhost/favicon.ico, strictSSL=false, rejectUnauthorized=false, Origin=Bundler
debug: in Bundler.send/async.reduce, memo = url=http://localhost/favicon.ico, strictSSL=false, rejectUnauthorized=false, Origin=Bundler, followRedirect=true, followAllRedirects=false, maxRedirects=10
error: Error making request to http://localhost/favicon.ico; Error: Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:1
```

**Comment by redwire** [comment]
Absolutely! This is definitely a fantastic idea. I'll make it a feature of the proxy server.

**Comment by redwire** [comment]
Did this in my last couple of commits.
The code for the error page can  be found at https://github.com/equalitie/bundler/blob/master/applications/error.html

**Comment by nosmo** [comment]
Looks good, thanks! :ship:
